export const Path = {
    INIT: '/',
    MAIN: '/main',
    FEEDBACKS: '/feedbacks',
    CALENDAR: '/calendar',
    TRAININGS: '/trainings',
    PROFILE: '/profile',
    SETTINGS: '/settings',
    AUTH: '/auth',
    REGISTRATION: '/auth/registration',
    CONFIRM_EMAIL: '/auth/confirm-email',
    CHANGE_PASSWORD: '/auth/change-password',
    ACHIEVEMENTS: '/achievements',
    RESULT: {
        LOGIN_ERROR: '/result/error-login',
        REGISTER_SUCCESS: '/result/success',
        REGISTER_ERROR: '/result/error',
        ERROR_USER_EXIST: '/result/error-user-exist',
        SUCCESS_CHANGE_PASSWORD: '/result/success-change-password',
        ERROR_EMAIL_NO_EXIST: '/result/error-check-email-no-exist',
        ERROR_CHECK_EMAIL: '/result/error-check-email',
        ERROR_CHANGE_PASSWORD: '/result/error-change-password',
    },
};
