export const dataTestId = {
    newReviewSubmitButton: 'new-review-submit-button',
    writeReviewButton: 'write-review',
    allReviewsButton: 'all-reviews-button',
    changePasswordInput: 'change-password',
    changeConfirmInput: 'change-confirm-password',
    changeSubmitButton: 'change-submit-button',
    verificationInput: 'verification-input',
    loginEmailInput: 'login-email',
    loginPasswordInput: 'login-password',
    loginRememberInput: 'login-remember',
    loginForgotButton: 'login-forgot-button',
    loginSubmitButton: 'login-submit-button',
    loginRetryButton: 'login-retry-button',

    registrationEmailInput: 'registration-email',
    registrationPasswordInput: 'registration-password',
    registrationConfirmInput: 'registration-confirm-password',
    writeReviewNotSavedModal: 'write-review-not-saved-modal',
    registrationSubmitButton: 'registration-submit-button',
    registrationRetryButton: 'registration-retry-button',
    registrationEnterButton: 'registration-enter-button',
    registrationBackButton: 'registration-back-button',
    changeEntryButton: 'change-entry-button',
    checkRetryButton: 'check-retry-button',
    checkBackButton: 'check-back-button',
    changeRetryButton: 'change-retry-button',
    loader: 'loader',
    alert: 'alert',
    alertTrainingSuccess: 'create-training-success-alert',
    tariffSider: 'tariff-sider',
    tariffCost: 'tariff-cost',
    tariffSubmitButton: 'tariff-submit',
    profileAvatar: 'profile-avatar',
    tariffTrainingsIcon: 'tariff-trainings-icon',
    tariffTrainings: 'tariff-trainings',
    tariffNotificationsIcon: 'tariff-notifications-icon',
    tariffNotifications: 'tariff-notifications',
    tariffThemeIcon: 'tariff-theme-icon',
    tariffTheme: 'tariff-theme',
    profileNameInput: 'profile-name',
    profileSurnameInput: 'profile-surname',
    tariffModalSuccess: 'tariff-modal-success',

    modalErrorUserTrainingButtonClose: 'modal-error-user-training-button-close',
    modalErrorUserTrainingTitle: 'modal-error-user-training-title',
    modalErrorUserTrainingSubtitle: 'modal-error-user-training-subtitle',
    modalErrorUserTrainingButton: 'modal-error-user-training-button',
    bigFileErrorClose: 'big-file-error-close',

    myTrainingsTable: 'my-trainings-table',
    createNewTrainingButton: 'create-new-training-button',
    updateMyTrainingTableIcon: 'update-my-training-table-icon',
    modalDrawerRight: 'modal-drawer-right',
    modalDrawerRightDatePicker: 'modal-drawer-right-date-picker',
    modalDrawerRightCheckboxPeriod: 'modal-drawer-right-checkbox-period',
    modalDrawerRightSelectPeriod: 'modal-drawer-right-select-period',
    modalDrawerRightButtonClose: 'modal-drawer-right-button-close',

    menuButtonTraining: 'menu-button-training',
    menuButtonCalendar: 'menu-button-calendar',
    menuButtonProfile: 'menu-button-profile',
    jointTrainingCards: 'joint-training-cards',
    notificationAboutJointTraining: 'notification-about-joint-training',
    jointTrainingReviewCard: 'joint-training-review-card',
    searchInput: 'search-input',
    modalInfo: 'partner-modal',
};
